module.exports = {
  collectCoverage: true,
  collectCoverageFrom: [
    '**/src/**/*.{ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!src/**/components/**/index.{js,jsx,ts,tsx}',
    '!src/**/components/**/styles.{js,ts}',
    '!src/**/components/**/__tests__/**/*.{js,jsx,ts,tsx}',
    '!**/reportWebVitals.{js, ts}',
    '!**/index.{js, ts}',
    '!**/coverage**',
    '!**/src/**/types/**',
    '!**/src/**/styles/**',
    '!**/src/**/constants/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['json-summary', 'text', 'html', 'lcov'],
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
  moduleNameMapper: { '\\.svg$': '<rootDir>/src/__mocks__/svgMock.ts', '^@/(.*)$': '<rootDir>/src/$1' },
  preset: 'ts-jest',
  setupFilesAfterEnv: ['<rootDir>/setupTests.ts'],
  testEnvironment: 'jsdom',
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/build/'],
  transform: {
    '^.+\\.(ts|tsx)?$': 'ts-jest',
  },
  transformIgnorePatterns: ['!node_modules/(?!@src/*.)', '^.+\\.module\\.(css|sass|scss)$'],
  verbose: true,
};
